version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - mvn package
      - mv target/demo-0.0.1-SNAPSHOT.war demo-0.0.1-SNAPSHOT.war
      - zip -ur demo-0.0.1-SNAPSHOT.war .ebextensions
artifacts:
  files:
    - '/**/*'
    #- .ebextensions/**/*
  base-directory: 'target/demo-0.0.1-SNAPSHOT'


  
    

     